### ISSUE TITLE
Installation takes too much for 0.0.4 (104MB)

### ISSUE THREAD

**Issue by ohtangza** [redpandatronicsuk/react-native-check-app-install#15]
It takes more than 15 minutes to install this library (https://registry.yarnpkg.com/react-native-check-app-install/-/react-native-check-app-install-0.0.4.tgz). Other libraries are less than 1MB, but why is it so heavy?

<img width="470" alt="screen shot 2018-08-22 at 12 51 06 pm" src="https://user-images.githubusercontent.com/1323963/44441921-165ede80-a60a-11e8-8465-8b0d44323873.png">

**Comment by ohtangza** [comment]
cc: @ghsdh3409

**Comment by redpandatronicsuk** [comment]
I think the issue was that the example folder, I added a `.npmignore' file now which should fix this
