### ISSUE TITLE
please remove 'example' folder from npm registry

### ISSUE THREAD

**Issue by smokokoi** [redpandatronicsuk/react-native-check-app-install#18]
it's taking a lot of space and impacting on the npm install speed.

thank you!

**Comment by ducpt2** [comment]
@smokokoi does this lib work for you? I test and it didn't work :(

**Comment by redpandatronicsuk** [comment]
Sorry for the long time it took me to answer this. I added a `.npmignore` file now, this should remove the example folder from the npm repository
