### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by levelasquez** [redpandatronicsuk/react-native-check-app-install#3]
Hi there,

After install the plugin and run `react-native link`, when i run `react-native run-android` i'm getting the following error:

`:react-native-check-app-install:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
dirProject/node_modules/react-native-check-app-install/android/src/main/java/com/rpt/reactnativecheckpackageinstallation/CheckPackageInstallationPackage.java:15: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error
:react-native-check-app-install:compileReleaseJavaWithJavac FAILED`

Here is some info about my environment:

plugin version: `0.0.3`

react-native versions
`react-native-cli: 2.0.1`
`react-native: 0.47.1`

Any help much appreciated.

**Comment by MrLucasFischer** [comment]
I had the same error, i went to the file the exception tells you (node_modules/react-native-check-app-install/android/src/main/java/com/rpt/reactnativecheckpackageinstallation/CheckPackageInstallationPackage.java) and removed the "@Override" at line 15.

Then in the console/terminal i did "cd android && gradlew clean && cd .. && react-native run-android" , it seemed to do the trick for me.

**Comment by levelasquez** [comment]
Hey @MrLucasFischer , thanks for answering but that not work for me, i had to do `cd android && /.gradlew clean && cd .. && react-native run-android` because `gradlew` tell me is not a command, so i had to add it `./` but still i am getting the same error.

I had to delete the property `@Override` from the public methods in `CheckPackageInstallationPackage.java` to make it work.

Like this:
Before:
```java
  @Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }

  @Override
  public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
    return Collections.emptyList();
  }

  @Override
  public List<NativeModule> createNativeModules(
                              ReactApplicationContext reactContext) {
    List<NativeModule> modules = new ArrayList<>();

    modules.add(new CheckPackageInstallationModule(reactContext));

    return modules;
  }
```
After:
```java
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }

  public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
    return Collections.emptyList();
  }

  public List<NativeModule> createNativeModules(
                              ReactApplicationContext reactContext) {
    List<NativeModule> modules = new ArrayList<>();

    modules.add(new CheckPackageInstallationModule(reactContext));

    return modules;
  }
```

But i don't know if this is the best solution.

**Comment by redpandatronicsuk** [comment]
Hi, thanks for reporting the issue. I have made the changes to make it compatible with RN 0.47+. Version 0.0.4 should work now.
