### ISSUE TITLE
[Android] Check Instagram always return false

### ISSUE THREAD

**Issue by Ahmed-Imam** [redpandatronicsuk/react-native-check-app-install#31]
`AppInstalledChecker.checkURLScheme('instagram').then((isInstalled) => isInstalled)`

this always reuturn false in Android

**Comment by marcelomunozr** [comment]
Hi !
for version 30 SDK for android, add in AndroidManifest.xml file new package for externals apps
in this file: **android/app/src/main/AndroidManifest.xml**

`    <queries>
        <package android:name="com.instagram.android" />
    </queries>`
