### ISSUE TITLE
IOS considered?

### ISSUE THREAD

**Issue by narek11** [redpandatronicsuk/react-native-check-app-install#9]
Can't seem to find files for ios installation?
Did you install it on IOS?
Does it work?
A better alternative to this?

**Comment by JPeer264** [comment]
For iOS you don't need any extra installation. It is done with `Linking`, which is actually pretty neat: [app-installed-checker.js#L21-L30](https://github.com/redpandatronicsuk/react-native-check-app-install/blob/12dba2b08ad9dda4795b85d5cda08b68175044d5/app-installed-checker.js#L21-L30)
